export enum Routes {
  BOTTOM_TAB = 'BOTTOM_TAB',

  ONBOARDING = 'ONBOARDING',
  ONBOARDING_SCREEN = 'ONBOARDING_SCREEN',

  HOME = 'HOME',
  HOME_SCREEN = 'HOME_SCREEN',

  AUTH = 'AUTH',
  SIGN_IN_SCREEN = 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN = 'SIGN_UP_SCREEN',

  RESET = 'RESET',
  RESET_PASSWORD = 'RESET_PASSWORD',
  SUCCESS_RESET_PASSWORD = 'SUCCESS_RESET_PASSWORD',


  MAIN = 'MAIN',
  PORTFOLIO = 'PORTFOLIO',
  PROFILE = 'PROFILE',

  CONFIRMATION_MODAL = 'CONFIRMATION_MODAL',
  PICKUP_TIME_MODAL = 'PICKUP_TIME_MODAL',
}

